export {default as rest} from './after'
export {default as rest} from './identity'
export {default as rest} from './partial'
export {default as rest} from './noop'
export {default as rest} from './rest'